project_id = "tiaojwumxgdnobknlyqp"

[functions.send-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.whatsapp-create-instance]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.provision-workspace]
verify_jwt = false

[functions.whatsapp-get-qr]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-send-audio]
verify_jwt = false

[functions.whatsapp-send-image]
verify_jwt = false

[functions.whatsapp-delete-instance]
verify_jwt = false

[functions.whatsapp-disconnect-instance]
verify_jwt = false
